[[headers]]
  # Define which origins are allowed to access your site
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    # You can replace "*" with a specific URL if you only want to allow a certain domain

  # Define which HTTP methods are allowed for cross-origin requests
  for = "/*"
    [headers.values]
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

  # Define which headers are allowed for cross-origin requests
  for = "/*"
    [headers.values]
    Access-Control-Allow-Headers = "Content-Type, Authorization"
